import Key from "./Keys";

function Keyboard({
  checkLetterInWord,
  resetGame,
  setGameState,
  resetCounter,
}) {
  return (
    <section className="keyboard" key={resetCounter}>
      <div className="keys">
        <Key
          setGameState={setGameState}
          letter={"Q"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"W"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"E"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"R"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"T"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"Y"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"U"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"I"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"O"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"P"}
          checkLetterInWord={checkLetterInWord}
        />
        <br />
        <Key
          setGameState={setGameState}
          letter={"A"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"S"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"D"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"F"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"G"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"H"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"J"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"K"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"L"}
          checkLetterInWord={checkLetterInWord}
        />
        <br />
        <Key
          setGameState={setGameState}
          letter={"Z"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"X"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"C"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"V"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"B"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"N"}
          checkLetterInWord={checkLetterInWord}
        />
        <Key
          setGameState={setGameState}
          letter={"M"}
          checkLetterInWord={checkLetterInWord}
        />
      </div>
      <div>
        <button className="resetButton" onClick={resetGame}>
          Reset Game
        </button>
      </div>
    </section>
  );
}

export default Keyboard;
